enum class Category(val type: TransactionType, val title: String) {
    SALARY(TransactionType.INCOME, "Salary"),
    FREELANCE(TransactionType.INCOME, "Freelance"),
    INVESTMENTS(TransactionType.INCOME, "Investments"),
    FAMILY_SUPPORT(TransactionType.INCOME, "Family support"),
    RENT(TransactionType.EXPENSE, "Rent"),
    FOOD(TransactionType.EXPENSE, "Food"),
    TRANSPORTATION(TransactionType.EXPENSE, "Transportation"),
    LIVING_ESSENTIALS(TransactionType.EXPENSE, "Living Essentials"),
    HEALTH_INSURANCE(TransactionType.EXPENSE, "Health & Insurance"),
    EDUCATION(TransactionType.EXPENSE, "Education"),
    SUBSCRIPTIONS(TransactionType.EXPENSE, "Subscriptions"),
    DEBT(TransactionType.EXPENSE, "Debt"),
    LOANS(TransactionType.EXPENSE, "Loans"),
    ENTERTAINMENT(TransactionType.EXPENSE, "Entertainment"),
    PETS(TransactionType.EXPENSE, "Pets"),
    GIFTS_DONATIONS(TransactionType.EXPENSE, "Gifts & Donations"),
}