# This is a basic workflow to help you get started with Actions

name: Run Kotlin Check Tests

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" and "development" branch
  push:
    branches: [ "main", "development" ]
  pull_request:
    branches: [ "main", "development" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java (for Kotlin)
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Install Kotlin compiler
        run: |
          sudo apt update
          sudo apt install -y kotlin
          
      - name: Compile Tests Validator
        run: |
          mkdir -p out
          kotlinc *.kt -include-runtime -d out/Tests.jar

      - name: Run Tests and Capture Output
        id: run-tests
        run: |
          set -o pipefail
          OUTPUT=$(kotlin kotlin out/Tests.jar | tee output.log)
          echo "$OUTPUT"
          echo "$OUTPUT" | grep -q "Failed" && exit 1 || echo "All tests passed"


